version: "3.9"
services:
  amotile:
    profiles: [amotile]
    image: localhost/sd-multi/amotile:latest
    build:
      context: .
      dockerfile: Dockerfile.amotile
      args:
        # Use a `.env` file to change this; see `env.example`:
        - GIT_CHECKOUT=${AMOTILE_HASH:-8c1bd17080cd40cf42b66d11f470f260e2982ce5}
        - AUTOMATIC1111_CHECKOUT=${AMOTILE_AUTOMATIC1111_HASH:-48dbf99e84045ee7af55bc5b1b86492a240e631e}
        - AMOTILE_BACKEND_CHECKOUT=${AMOTILE_BACKEND_HASH:-c6b11731a8a76b6470e89c4c8a2c931672ec125b}
    init: true
    ports:
      - "4000:4000"
      - "4001:4001"
      - "7860:7860"
    volumes:
      - ./res:/res:ro
      - ./output/amotile:/root/stable-diffusion-backend/data
      - cache-amotile:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  automatic1111:
    profiles: [automatic1111]
    image: localhost/sd-multi/automatic1111:latest
    build:
      context: .
      dockerfile: Dockerfile.automatic1111
      args:
        # Use a `.env` file to change this; see `env.example`:
        - GIT_CHECKOUT=${AUTOMATIC1111_HASH:-3e15f8e0f5cc87507f77546d92435670644dbd18}
        - TXT2VECTORGRAPHICS_CHECKOUT=${AUTOMATIC1111_TXT2VECTORGRAPHICS_HASH:-2b780584f603b9abebba02527f3e0c3eed63426b}
        - DEFORUM_CHECKOUT=${AUTOMATIC1111_DEFORUM_HASH:-7a089c134481767bd8e3bf6aa1afc064886a78aa}
    init: true
    ports:
      - "7860:7860"
    volumes:
      - ./res:/res:ro
      - ./res/checkpoints:/res/checkpoints:rw
      - ./output:/root/stable-diffusion-webui/outputs
      - cache-automatic1111:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  hlky:
    profiles: [hlky]
    image: localhost/sd-multi/hlky:latest
    build:
      context: .
      dockerfile: Dockerfile.hlky
      args:
        # Use a `.env` file to change this; see `env.example`:
        - GIT_CHECKOUT=${HLKY_HASH:-8229d1bd9266021bda5bd0bbfc106ccba01c1bf5}
    init: true
    ports:
      - "7860:7860"
      - "8501:8501"
    volumes:
      - ./res:/res:ro
      - ./output:/root/stable-diffusion-webui/outputs
      - cache-hlky:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  lstein:
    profiles: [lstein]
    image: localhost/sd-multi/lstein:latest
    build:
      context: .
      dockerfile: Dockerfile.lstein
      args:
        # Use a `.env` file to change this; see `env.example`:
        - GIT_CHECKOUT=${LSTEIN_HASH:-e4ed0943e2d87b59d8f4f482e8d1fdb962ba82ea}
    init: true
    ports:
      - "9090:9090"
    volumes:
      - ./res:/res:ro
      - ./output:/root/stable-diffusion-webui/outputs
      - cache-lstein:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  osi1880vr:
    profiles: [osi1880vr]
    image: localhost/sd-multi/osi1880vr:latest
    build:
      context: .
      dockerfile: Dockerfile.osi1880vr
      args:
        # Use a `.env` file to change this; see `env.example`:
        - GIT_CHECKOUT=${OSI1880VR_HASH:-ea69f9271d29517a7cb4a3ad6c790272e2f82333}
    ports:
      - "8501:8501"
    volumes:
      - ./res:/res:ro
      - ./output:/root/stable-diffusion-webui/outputs
      - cache-osi1880vr:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  cache-amotile:
  cache-automatic1111:
  cache-hlky:
  cache-lstein:
  cache-osi1880vr:
