version: "3.9"
services:
  amotile:
    profiles: [amotile]
    image: localhost/sd-multi/amotile:latest
    build:
      context: .
      dockerfile: Dockerfile.amotile
      args:
        # Use a `.env` file to change this; see `env.example`:
        - GIT_CHECKOUT=${AMOTILE_HASH:-5dff371f19933a342bd17620597a9fbbe431355e}
        - AUTOMATIC1111_CHECKOUT=${AMOTILE_AUTOMATIC1111_HASH:-494afccbc1d7b0aca4ffeb3d8354b09c414d95f4}
        - AMOTILE_BACKEND_CHECKOUT=${AMOTILE_BACKEND_HASH:-080f063b74b058482600feb0832d6927e58c91ea}
    init: true
    ports:
      - "4000:4000"
      - "4001:4001"
    volumes:
      - ./res:/res:ro
      - ./output/amotile:/root/stable-diffusion-backend/data
      - cache-amotile:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  automatic1111:
    profiles: [automatic1111]
    image: localhost/sd-multi/automatic1111:latest
    build:
      context: .
      dockerfile: Dockerfile.automatic1111
      args:
        # Use a `.env` file to change this; see `env.example`:
        - GIT_CHECKOUT=${AUTOMATIC1111_HASH:-be1596ce30b1ead6998da0c62003003dcce5eb2c}
        - TXT2VECTORGRAPHICS_CHECKOUT=${AUTOMATIC1111_TXT2VECTORGRAPHICS_HASH:-059222e67a36823473e711d4ba69226a17b8bdfe}
        - DEFORUM_CHECKOUT=${AUTOMATIC1111_DEFORUM_HASH:-245f0535d3549d969707ceabc903b2b2a182d55d}
    ports:
      - "7860:7860"
    volumes:
      - ./res:/res:ro
      - ./output:/root/stable-diffusion-webui/outputs
      - cache-automatic1111:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  hlky:
    profiles: [hlky]
    image: localhost/sd-multi/hlky:latest
    build:
      context: .
      dockerfile: Dockerfile.hlky
      args:
        # Use a `.env` file to change this; see `env.example`:
        - GIT_CHECKOUT=${HLKY_HASH:-bcd708f34de80b41c02cf86a79ec4de4438aebe5}
    ports:
      - "7860:7860"
      - "8501:8501"
    volumes:
      - ./res:/res:ro
      - ./output:/root/stable-diffusion-webui/outputs
      - cache-hlky:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  lstein:
    profiles: [lstein]
    image: localhost/sd-multi/lstein:latest
    build:
      context: .
      dockerfile: Dockerfile.lstein
      args:
        # Use a `.env` file to change this; see `env.example`:
        - GIT_CHECKOUT=${LSTEIN_HASH:-94bad8555a8832eca01ed7da6797f65cf6bb9cfb}
    ports:
      - "9090:9090"
    volumes:
      - ./res:/res:ro
      - ./output:/root/stable-diffusion-webui/outputs
      - cache-lstein:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  osi1880vr:
    profiles: [osi1880vr]
    image: localhost/sd-multi/osi1880vr:latest
    build:
      context: .
      dockerfile: Dockerfile.osi1880vr
      args:
        # Use a `.env` file to change this; see `env.example`:
        - GIT_CHECKOUT=${OSI1880VR_HASH:-ea69f9271d29517a7cb4a3ad6c790272e2f82333}
    ports:
      - "8501:8501"
    volumes:
      - ./res:/res:ro
      - ./output:/root/stable-diffusion-webui/outputs
      - cache-osi1880vr:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  cache-amotile:
  cache-automatic1111:
  cache-hlky:
  cache-lstein:
  cache-osi1880vr:
